/**
 * Sonovate Technical Project Service
 * Sonovate Technical Project Service swagger definitions
 *
 * OpenAPI spec version: 0.0.0
 * Contact: dick@ecgtheow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SonovatetestPlacement } from './sonovatetestPlacement';


/**
 * A client that owns placements
 */
export interface SonovatetestClient {
    /**
     * Client ID
     */
    id?: number;

    /**
     * Client name
     */
    name?: string;

    /**
     * Placements owned by this client
     */
    placements?: Array<SonovatetestPlacement>;

}
