/**
 * Sonovate Technical Project Service
 * Sonovate Technical Project Service swagger definitions
 *
 * OpenAPI spec version: 0.0.0
 * Contact: dick@ecgtheow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SonovatetestCandidate } from './sonovatetestCandidate';
import { SonovatetestClient } from './sonovatetestClient';


/**
 * A placement
 */
export interface SonovatetestPlacement {
    /**
     * Placement ID
     */
    id?: number;

    /**
     * Placement job title
     */
    jobtitle?: string;

    /**
     * Placement start date as ms since the Unix epoch
     */
    startdate?: number;

    /**
     * Placement end date as ms since Unix epoch
     */
    enddate?: number;

    /**
     * Placement type
     */
    placementtype?: SonovatetestPlacement.PlacementtypeEnum;

    /**
     * Placement candidate
     */
    candidate?: SonovatetestCandidate;

    /**
     * Placement client
     */
    client?: SonovatetestClient;

    /**
     * Placement client ID
     */
    clientid?: number;

    /**
     * Placement candidate ID
     */
    candidateid?: number;

}
export namespace SonovatetestPlacement {
    export enum PlacementtypeEnum {
        Weekly = <any> 'Weekly',
        Monthly = <any> 'Monthly'
    }
}
