#!/bin/sh

DIE=0

(which mono) < /dev/null > /dev/null 2>&1 || {
  echo
  echo "**Error**: No mono found on PATH"
  DIE=1
}

(which xbuild) < /dev/null > /dev/null 2>&1 || {
  echo
  echo "**Error**: No xbuild found on PATH"
  DIE=1
}

if test "$DIE" -eq 1; then
  exit 1
fi

cd server
xbuild || { echo "**Error**: xbuild failed."; exit 1; }

cd sonovatetest/bin/Debug
mono sonovatetest.exe
